# .github/workflows/snake.yml

name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 👇 This permissions block is new and NECESSARY to fix the error
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4 # Updated to a newer version

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Pushes the generated file to the output branch
      - uses: crazy-max/ghaction-github-pages@v4 # Updated to a newer version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
